In [1]:
from google.colab import files

uploaded = files.upload()

Saving Website Phishing.csv to Website Phishing.csv


In [2]:
import numpy as np

import pandas as pd

from sklearn.preprocessing import StandardScaler

from sklearn import preprocessing

from sklearn.preprocessing import LabelEncoder

dataset = pd.read_csv("Website Phishing.csv",sep=",")

X = dataset.iloc[:,1:9]

y = dataset.iloc[:,9]

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.25,random_state = 0)

In [3]:
from sklearn.tree import DecisionTreeClassifier

classifier = DecisionTreeClassifier(criterion ='entropy', random_state = 0)

classifier.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [4]:
y_pred = classifier.predict(X_test)

from sklearn.metrics import confusion_matrix

matrix = confusion_matrix(y_test, y_pred)

accuracy = np.trace(matrix) / float(np.sum(matrix))

print("Cofusion Matrix")

print(matrix)

print("The accuracy is: {:.2%}".format(accuracy))

Cofusion Matrix
[[145   4  22]
 [  5  21   2]
 [ 25   3 112]]
The accuracy is: 82.01%
